**THEORATICAL** **QUESTIONS**

1/ Explain the purpose and advantages of NumPy in scientific--------- for numerical operations?
- NumPy handles advanced mathematical operations such as matrix multiplication,eigenvalue calculations and differential equations.

NumPy provides a rich collection of mathematical functions,making it an indispensable tool for scientific computing,linear algebra,statistics,and NumPy for simulations,solving differential equations,numerical integration.

It is also used in data science in order to work through numerical analyses and functions,such as creating and working with arrays,returning descriptive statistics and variety of machine learning models and mathematical formulas.

It is a Python package for scientific computing,it provides an efficient multi-dimensional array of objects as well as variety of functions for workinf with them,NumPy array is an array of values that is homogenous, axes are the dimensions of an array in NumPy

2/ Compare the np.mean() and np.average() functions--------others?

- In NumPy library there are two functions np.mean() and np.average() are two functions present these two were doing nearly same job of calculating mean/average.

np.mean()- This function is used to calculate arithmetic mean and all elements have equal weight, weight cannot be passed through the parameter of the given function. np.mean(arr,axis=None)

np.average()- This functions used to calculate the arithmetic mean as well as weighted average, all elements may or may not have equal weight, weight can passed through the parameter of the given functions. np.average(arr,axis=None,weights=None)

3/ Describe the methods for-----------2D array.

- flip()function: it reverse the order of array elements along the specified axis,preserving the shape of the array.

list slicing method: this method makes a copy of the list instead of sorting it in order, to accommodate all of the current components, making a clone requires additional room.

flipud function: the flip() function flips the array in up-down direction, shape preserved.

In [ ]:
# 1D and 2D array

import numpy as np

#creating the list
list = [100,200,300,400,500,]

#creating 1-d array
n = np.array(list)
print(n)

import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)


[100 200 300 400 500]
[[1 2 3 4]
 [5 6 7 8]]


4/ How can determine the data type of elements in a numpy-------------performance.

- by using
 dtype
 array function array()


In [ ]:
# by using dtype

import numpy as np

arr = np.array([1,2,3,4,5])
print('Array:', arr)
print('Datatype:', arr.dtype)

Array: [1 2 3 4 5]
Datatype: int64


In [ ]:
# by using array()

import numpy as np
arr = np.array([1,2,3,5,7,8,9], dtype='S')
print("Array:", arr)
print("Datatype:", arr.dtype)


Array: [b'1' b'2' b'3' b'5' b'7' b'8' b'9']
Datatype: |S1


5/ Define ndarray in NumPy--------------------python list?

- An array class in NumPy is called as ndarray, elements in numpy arrays are accessed by using square brackets and can be initialized by using python lists.

various ways to create arrays in NumPy
-we can create an array from regular python list or tuple using the array function,the type of resulting array is deduced from the type of the elements in the sequence,

arange: returns evenly spaced values with in a given interval, step size is specified,
linespace: num no. of elements are returned.

flatten array: we can use flatten method to get a copy of array collapsed into one dimension.

Array indexing:

Slicing- NumPy array can be sliced,as an array can be multidimensional, we get need to specify a slice for each dimension of the array

Integer array indexing- in this lists are passed for indexing for each dimension, one to one mapping of corresponding elements is done to construct a new arbitrary array.

Boolean array indexing- it is used when we want to pick elements from an array which satisfy some conditions

6/ Analyze the performance benefits ------------ operations.

- Advantages of using Numpy arrays over python lists are:

consumes less memory, fast as compared to the pyhton list, convenient to use,

In Python list list is built-in data structure that can hold elements of varying data types, but Python NumPy library supports optimized numerical array and matrix operations.

The NumPy array store elements of the same datatypes, making them more compact and memory-efficient than lists.

Numpy arrays have fixed datatype,reducing memory overhead by eliminating the need to store type information for each element.

NumPy arrays are optimized for numerical computations,with efficient element-wise operations and mathematical functions.


7/ Compare vstack() and hstack() functions in numpy-------------examples.
-

numpy.vstack() function is used to stack the sequence of input arrays vertically to make single array.

numpy.hstack() function is used to stack the sequence of input array horizontally to make a single array.



In [ ]:
# vstack

import numpy as np
in_arr1 = np.array([1,2,3,4])
print ("1st Input array : \n", in_arr1)

in_arr2 = np.array([5,6,7,8])
print ("2nd Input array : \n", in_arr2)

out_arr = np.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)

out_arr = np.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)



1st Input array : 
 [1 2 3 4]
2nd Input array : 
 [5 6 7 8]
Output vertically stacked array:
  [[1 2 3 4]
 [5 6 7 8]]
Output horizontally stacked array:
  [1 2 3 4 5 6 7 8]


8/ Explain the difference between fliplr()and flipud()--------------dimensions.
-
numpy.fliplr() is used to flip array in left-right direction,shape preserved

array : [array_like]Input
array, we want to flip

numpy.flipud() is used to flip ndarray vertically, up and down, it will return a view shares memory with the original array,changing one value changes the other.

In [ ]:
# fliplr() method

import numpy as np
array = np.arange(8).reshape((2,2,2))
print("Original array : \n", array)
print("Flipped array : \n", np.fliplr(array))

print("Flipped array : \n", np.flipud(array))

Original array : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Flipped array : 
 [[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]
Flipped array : 
 [[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]


9/ Discuss the functionality of array_split()method-------uneven splits?
- Array splitting in numpy is like a slice of cake or something means arrays as cake and we slice it by using split() method

The split(),hsplit(),vsplit(),dsplit() functions are important tools for dividing arrays along various axes and dimensions, these functions were particularly useful when working with one-dimensional array, matrices or high dimensional datasets

There are many methods to split numpy array;

split numpy array using numpy.split()
split numpy array using numpy.array_split()
split numpy array using numpy.vsplit()
split numpy array using numpy.hsplit()


In [ ]:
import numpy as np
array = np.arange(20)
result = np.array_split(array, 5)
print("Array:")
print(array)
print("\nResult after numpy.array_split():")
print(result)

Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Result after numpy.array_split():
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15]), array([16, 17, 18, 19])]


10/ Explain the concept of vectorization and broadcasting---------array operations?
-
Vectorization is process of converting an algorithm from operating on a single value at a time to operating on a set of values(vector) at one time.

It also use the concept of broadcasting for performing operations in arrays of different sizes.

The numpy vectorize function (np.vectorize) is provided by python it accepts a nested sequence of objects or a numpy array as input and returns a single numpy array or a tuple of numpy array as a output.

Broadcasting provides a mean of vectorizing array operations, it does this without making needless copies of data which leads to efficient algorithm implementation, the broadcasting over multiple array in numpy extension can raise cases where broadcasting is a bad idea because it lead to inefficient use of memory that slows down computation.

The arrays can be broadcasted together if they are compatible with all dimensions, after broadcasting each array behaves oas is it had a shape equal to the element-wise maximum of shapes of the two input arrays.

In [ ]:
# broadcsting of 1D array

import numpy as np
a = np.array([17,18,19])
print(a)
b = 3
print(b)

c = a + b
print(c)

[17 18 19]
3
[20 21 22]


**PRACTICAL QUESTIONS**

1/ create a 3*3numpy array with random integers between 1 and 100 , then interchange its rows and columns.      

In [5]:
import numpy as np
x = np.random.randint(1,100,(3,3,3))
print(x)
result = np.swapaxes(x,0,1)
print(result)

[[[ 1 16 55]
  [73 83 67]
  [50 69  3]]

 [[25 91 96]
  [95 11 50]
  [75 91 37]]

 [[17 57 64]
  [26 80 44]
  [82 49 93]]]
[[[ 1 16 55]
  [25 91 96]
  [17 57 64]]

 [[73 83 67]
  [95 11 50]
  [26 80 44]]

 [[50 69  3]
  [75 91 37]
  [82 49 93]]]


2/ Generate a 1d numpy array with 10 elements,reshape it into a 2*5 array then into 5*2 array.

In [6]:
import numpy as np
array = np.arange(10)
print(array)
array = array.reshape(2,5)
print(array)
array = array.reshape(5,2)
print(array)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3/ create a 4*4numpy array with random float values,add a border of zeros around it resulting it into a 6*6 array.

In [7]:
import numpy as np
x = np.random.rand(4,4)
print(x)
y = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(y)

[[0.11684912 0.09207504 0.6273814  0.48668934]
 [0.36788103 0.86947569 0.45361134 0.33573209]
 [0.96909448 0.98555166 0.03842187 0.62291753]
 [0.81480066 0.60662318 0.05014003 0.06242845]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.11684912 0.09207504 0.6273814  0.48668934 0.        ]
 [0.         0.36788103 0.86947569 0.45361134 0.33573209 0.        ]
 [0.         0.96909448 0.98555166 0.03842187 0.62291753 0.        ]
 [0.         0.81480066 0.60662318 0.05014003 0.06242845 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4/ using numpy create an array of integer from 10 to 60 with a step of 5.

In [1]:
import numpy as np
array = np.arange(10,60,5)
print(array)

[10 15 20 25 30 35 40 45 50 55]


5/ Create a numpy array of strings[python,numpy,pandas], apply different case transformation to each element.

In [8]:
import numpy as np
x = np.array(['python','numpy','pandas'])
print(x)
print(np.char.upper(x))
print(np.char.lower(x))
print(np.char.title(x))
print(np.char.capitalize(x))

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']
['Python' 'Numpy' 'Pandas']


6/ Generate a numpy array of words insert a space between each character of every word in the array.

In [9]:
import numpy as np
x = np.array(['python','numpy','pandas'])
print(x)
new_array = np.char.join(' ',x)
print(new_array)



['python' 'numpy' 'pandas']
['p y t h o n' 'n u m p y' 'p a n d a s']


7/ Create two 2d numpy arrays and perform element-wise addition,subtraction,multiplication,and division.

In [11]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
print(x)
print(y)
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8/ use numpy to create a 5*5 identity matrix, then extract its diagonal elements.

In [12]:
import numpy as np
x = np.eye(5)
print(x)
print(np.diag(x))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


9/ generate a numpy array of 100 random integers between 0 and 1000, find and display all prime numbers in this array.

In [15]:
import numpy as np
x = np.random.randint(0,1000,100)
print(x)
display_prime = []
for num in x:
  if num > 1:
    for i in range(2,num):
      if (num % i) == 0:
        break
    else:
      display_prime.append(num)

[886 284 867 951 721  57 158 565 595 860 165 325 254 874 737 136 649 241
 513 733 935 864  68 914 118 493 939   1 346 239 368 961 639 378 609  61
 436  33 382 699 740  11 249 392 665 257 212 779 606 695 129 180 420  76
 830 835 559  44 751 719 711 892 460 325 643 127 525 153 207 872 190  87
 230 227 648 213 618 577 658 784 170  23 120 764  74 324 596 931  53 462
 158 938 676 227 456 205 341 740 485 133]


10/ create a numpy array representing daily temperature for a month,calculate and display the weekly averages.

In [18]:
import random
import numpy as np
temperatures = [
    random.randint(20, 30) for _ in range(30)
]
print(temperatures)
print(np.mean(temperatures))
print(np.median(temperatures))
print(np.std(temperatures))

averages = np.mean(temperatures)
print(averages)




[21, 20, 29, 24, 23, 22, 20, 30, 21, 21, 22, 21, 22, 30, 22, 22, 22, 20, 28, 23, 28, 28, 23, 28, 27, 28, 29, 26, 21, 26]
24.233333333333334
23.0
3.3534393621408394
24.233333333333334
